apiVersion: v1
kind: Service
metadata:
  name: gateway-svc-helm
  namespace: {{ .Release.namespace }}
  labels:
    app: gateway-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      name: http
    - port: 2112
      name: prometheus-port
  selector:
    app: gateway-app