apiVersion: v1
kind: Service
metadata:
  name: payment-svc-helm
  namespace: {{ .Release.Namespace }}
  labels:
    app: payment-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      name: grpc
    - port: 2112
      name: prometheus-port
  selector:
    app: payment-app