apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  namespace: ecommerce-project
  annotations:
    cert-manager.io/cluster-issuer: ecommerce-production
spec:
  ingressClassName: external-nginx
  rules:
    - host: testk8s.mangoanywhere.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway-svc-helm
                port:
                  number: 12340
    - host: rabbitmq.testk8s.mangoanywhere.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
          
    - host: jaeger.testk8s.mangoanywhere.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jaeger-service
                port:
                  number: 16686
    - host: grafana.testk8s.mangoanywhere.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 80
    - host: prometheus.testk8s.mangoanywhere.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-service
                port:
                  number: 9090
  tls:
    - hosts:
        - testk8s.mangoanywhere.com
      secretName: testk8s-mangoanywhere-com
    - hosts:
        - rabbitmq.testk8s.mangoanywhere.com
      secretName: rabbitmq-testk8s-mangoanywhere-com
    - hosts:
        - jaeger.testk8s.mangoanywhere.com
      secretName: jaeger-testk8s-mangoanywhere-com
    - hosts:
        - grafana.testk8s.mangoanywhere.com
      secretName: grafana-testk8s-mangoanywhere-com
    - hosts:
        - prometheus.testk8s.mangoanywhere.com
      secretName: prometheus-testk8s-mangoanywhere-com