apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: ecommerce-project
spec:
  type: ExternalName
  externalName: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: ecommerce-project
spec:
  type: ExternalName
  externalName: kube-prometheus-stack-prometheus.monitoring.svc.cluster.local
  ports:
    - port: 9090
      targetPort: 9090
